// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using fiap.gerenciador_trafego.Data;

#nullable disable

namespace fiap.gerenciador_trafego.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241208022329_CriaçãoDeTabelas")]
    partial class CriaçãoDeTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.AcidenteModel", b =>
                {
                    b.Property<int>("IdRegAcidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_reg_acidente");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegAcidente"));

                    b.Property<string>("DsGravidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("ds_gravidade");

                    b.Property<string>("DsLocalAcidente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("ds_local_acidente");

                    b.Property<DateTime>("DtAcidente")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_acidente");

                    b.Property<int>("NrFluxoImpactado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nr_fluxo_impactado");

                    b.Property<int?>("SemaforoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("t_gti_semaforo_id_semaforo");

                    b.HasKey("IdRegAcidente")
                        .HasName("pk_t_gti_reg_acidente");

                    b.HasIndex("SemaforoId");

                    b.ToTable("t_gti_reg_acidente", (string)null);
                });

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.ClimaModel", b =>
                {
                    b.Property<long>("IdClima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_clima");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdClima"));

                    b.Property<string>("DsCondicao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<DateTime>("DtRegistro")
                        .HasColumnType("date");

                    b.Property<decimal>("NrTemperatura")
                        .HasColumnType("number(10,2)");

                    b.Property<double>("NrUmidade")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("IdClima")
                        .HasName("pk_t_gti_clima");

                    b.ToTable("t_gti_clima", (string)null);
                });

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.RotaModel", b =>
                {
                    b.Property<int>("IdRota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_rota");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRota"));

                    b.Property<int?>("AcidenteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("t_reg_acidente_id_reg_acidente");

                    b.Property<string>("DsDescricaoRota")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ds_descricao_rota");

                    b.Property<string>("DsStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasDefaultValue("ABERTA")
                        .HasColumnName("ds_status");

                    b.HasKey("IdRota")
                        .HasName("pk_t_gti_rota");

                    b.HasIndex("AcidenteId");

                    b.ToTable("t_gti_rota", (string)null);
                });

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.SemaforoModel", b =>
                {
                    b.Property<int>("IdSemaforo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_semaforo");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSemaforo"));

                    b.Property<long?>("ClimaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("t_gti_clima_id_clima");

                    b.Property<string>("DsEstado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasDefaultValue("vermelho")
                        .HasColumnName("ds_estado");

                    b.Property<string>("DsLocalizacao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("ds_localizacao");

                    b.Property<DateTime>("DtUltAtualizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_ult_atualizacao");

                    b.Property<int>("NrDuracaoEstado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nr_duracao_estado");

                    b.HasKey("IdSemaforo")
                        .HasName("pk_t_gti_semaforo");

                    b.HasIndex("ClimaId");

                    b.ToTable("t_gti_semaforo", (string)null);
                });

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.SensorTrafegoModel", b =>
                {
                    b.Property<int>("IdSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_sensor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSensor"));

                    b.Property<DateTime>("DtDeteccao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_deteccao");

                    b.Property<int>("NrVisibilidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nr_visibilidade");

                    b.Property<int>("QtFluxoVeiculos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("qt_fluxo_veiculos");

                    b.Property<int>("SemaforoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("t_gti_semaforo_id_semaforo");

                    b.HasKey("IdSensor")
                        .HasName("pk_t_gti_sensor_trafego");

                    b.HasIndex("SemaforoId");

                    b.ToTable("t_gti_sensor_trafego", (string)null);
                });

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("UserID")
                        .HasName("pk_t_usuario");

                    b.ToTable("t_usuario", (string)null);
                });

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.AcidenteModel", b =>
                {
                    b.HasOne("fiap.gerenciador_trafego.Models.SemaforoModel", "Semaforo")
                        .WithMany()
                        .HasForeignKey("SemaforoId");

                    b.Navigation("Semaforo");
                });

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.RotaModel", b =>
                {
                    b.HasOne("fiap.gerenciador_trafego.Models.AcidenteModel", "Acidente")
                        .WithMany()
                        .HasForeignKey("AcidenteId");

                    b.Navigation("Acidente");
                });

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.SemaforoModel", b =>
                {
                    b.HasOne("fiap.gerenciador_trafego.Models.ClimaModel", "Clima")
                        .WithMany()
                        .HasForeignKey("ClimaId");

                    b.Navigation("Clima");
                });

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.SensorTrafegoModel", b =>
                {
                    b.HasOne("fiap.gerenciador_trafego.Models.SemaforoModel", "Semaforo")
                        .WithMany()
                        .HasForeignKey("SemaforoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semaforo");
                });
#pragma warning restore 612, 618
        }
    }
}
