// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using fiap.gerenciador_trafego.Data;

#nullable disable

namespace fiap.gerenciador_trafego.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241207232124_Clima")]
    partial class Clima
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fiap.gerenciador_trafego.Models.ClimaModel", b =>
                {
                    b.Property<long>("IdClima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_clima");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdClima"));

                    b.Property<string>("DsCondicao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<DateTime>("DtRegistro")
                        .HasColumnType("date");

                    b.Property<decimal>("NrTemperatura")
                        .HasColumnType("number(10,2)");

                    b.Property<double>("NrUmidade")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("IdClima")
                        .HasName("pk_t_gti_clima");

                    b.ToTable("t_gti_clima", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
